FORMAT: 1A
HOST: localhost:10018/

# manhuagui-backend (1.0)

An unofficial backend for manhuagui written in golang/gin

[Aoi-hosizora - Website](https://github.com/Aoi-hosizora)

[Send email to Aoi-hosizora](mailto:aoihosizora@hotmail.com)

# Group Manga

manga-controller

## Get all manga pages [/v1/manga{?page,order}]

### Get all manga pages [GET]

`GET /v1/manga`

+ Parameters

    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<_Page<TinyMangaPageDto>>)

    + Headers

    + Body

## Get manga page [/v1/manga/{mid}]

### Get manga page [GET]

`GET /v1/manga/{mid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<MangaPageDto>)

    + Headers

    + Body

## Get manga chapter [/v1/manga/{mid}/{cid}]

### Get manga chapter [GET]

`GET /v1/manga/{mid}/{cid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)
    + cid (number, required) - manga chapter id
        (format: int64)

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<MangaChapterDto>)

    + Headers

    + Body

# Group MangaList

manga-list-controller

## Get hot serial mangas [/v1/list/serial]

### Get hot serial mangas [GET]

`GET /v1/list/serial`

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<MangaPageGroupListDto>)

    + Headers

    + Body

## Get finished mangas [/v1/list/finish]

### Get finished mangas [GET]

`GET /v1/list/finish`

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<MangaPageGroupListDto>)

    + Headers

    + Body

## Get latest mangas [/v1/list/latest]

### Get latest mangas [GET]

`GET /v1/list/latest`

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<MangaPageGroupListDto>)

    + Headers

    + Body

## Get latest mangas [/v1/list/updated{?page,limit}]

### Get latest mangas [GET]

`GET /v1/list/updated`

+ Parameters

    + page (number, optional) - current page
        (format: int32)
    + limit (number, optional) - page size
        (format: int32)

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<_Page<TinyMangaPageDto>>)

    + Headers

    + Body

# Group Category

category-controller

## Get genres [/v1/category/genre]

### Get genres [GET]

`GET /v1/category/genre`

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<_Page<CategoryDto>>)

    + Headers

    + Body

## Get zones [/v1/category/zone]

### Get zones [GET]

`GET /v1/category/zone`

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<_Page<CategoryDto>>)

    + Headers

    + Body

## Get ages [/v1/category/age]

### Get ages [GET]

`GET /v1/category/age`

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<_Page<CategoryDto>>)

    + Headers

    + Body

## Get genre mangas [/v1/category/genre/{genre}{?zone,age,status,page,order}]

### Get genre mangas [GET]

`GET /v1/category/genre/{genre}`

+ Parameters

    + genre (string, required) - genre name
    + zone (string, optional) - manga zone
    + age (string, optional) - manga age, (shaonv|shaonian|qingnian|ertong|tongyong)
    + status (string, optional) - manga status, (lianzai|wanjie)
    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<_Page<TinyMangaPageDto>>)

    + Headers

    + Body

# Group Search

search-controller

## Search mangas [/v1/search/{keyword}{?page,order}]

### Search mangas [GET]

`GET /v1/search/{keyword}`

+ Parameters

    + keyword (string, required) - search keyword
    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<_Page<SmallMangaPageDto>>)

    + Headers

    + Body

# Group Author

author-controller

## Get all authors [/v1/author{?page,order}]

### Get all authors [GET]

`GET /v1/author`

+ Parameters

    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (_Result<_Page<SmallAuthorDto>>)

    + Headers

    + Body

# Data Structures

## Result (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message

## SmallAuthorDto (object)

+ aid (number, required) - author id
    (format: int64)
+ name (string, required) - author name
+ zone (string, required) - author zone
+ url (string, required) - author url
+ manga_count (number, required) - author manga count
    (format: int32)
+ newest_date (string, required) - author update newest date

## TinyAuthorDto (object)

+ aid (number, required) - author id
    (format: int64)
+ name (string, required) - author name
+ url (string, required) - author url

## CategoryDto (object)

+ name (string, required) - category name
+ title (string, required) - category title
+ url (string, required) - category link

## MangaPageDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ title (string, required) - manga name
+ cover (string, required) - manga cover
+ url (string, required) - manga link
+ publish_year (string, required) - manga publish year
+ manga_zone (string, required) - manga zone
+ genres (array[CategoryDto], required) - manga genres
+ authors (array[TinyAuthorDto], required) - manga authors
+ alias (string, required) - manga alias name
+ finished (boolean, required) - manga is finished
+ newest_chapter (string, required) - manga last update chapter
+ newest_date (string, required) - manga last update date
+ brief_introduction (string, required) - manga brief introduction
+ introduction (string, required) - manga introduction
+ manga_rank (string, required) - manga rank
+ average_score (number, required) - manga average score
    (format: float)
+ score_count (number, required) - manga score count
    (format: int32)
+ per_scores (array[number], required) - manga per scores, from 0 to 5
+ chapter_groups (array[MangaChapterGroupDto], required) - manga chapter groups

## MangaChapterDto (object)

+ cid (number, required) - chapter id
    (format: int64)
+ title (string, required) - chapter name
+ mid (number, required) - manga id
    (format: int64)
+ manga_title (string, required) - manga name
+ url (string, required) - chapter link
+ pages (array[string], required) - chapter pages
+ page_count (number, required) - chapter pages count
    (format: int32)
+ next_cid (number, required) - next chapter id
    (format: int64)
+ prev_cid (number, required) - prev chapter id
    (format: int64)

## SmallMangaPageDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ title (string, required) - manga name
+ cover (string, required) - manga cover
+ url (string, required) - manga link
+ publish_year (string, required) - manga publish year
+ manga_zone (string, required) - manga zone
+ genres (array[CategoryDto], required) - manga genres
+ authors (array[TinyAuthorDto], required) - manga authors
+ finished (boolean, required) - manga is finished
+ newest_chapter (string, required) - manga last update chapter
+ newest_date (string, required) - manga last update date
+ brief_introduction (string, required) - manga brief introduction

## TinyMangaPageDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ title (string, required) - manga name
+ cover (string, required) - manga cover
+ url (string, required) - manga link
+ finished (boolean, required) - manga is finished
+ newest_chapter (string, required) - manga last update chapter
+ newest_date (string, required) - manga last update date

## TinyMangaChapterDto (object)

+ cid (number, required) - chapter id
    (format: int64)
+ title (string, required) - chapter name
+ mid (number, required) - manga id
    (format: int64)
+ url (string, required) - chapter link
+ page_count (number, required) - chapter pages count
    (format: int32)
+ is_new (boolean, required) - chapter is uploaded newly

## MangaPageGroupDto (object)

+ title (string, required) - group title
+ mangas (array[TinyMangaChapterDto], required) - group mangas

## MangaChapterGroupDto (object)

+ title (string, required) - group title
+ chapters (array[TinyMangaChapterDto], required) - group chapters

## MangaPageGroupListDto (object)

+ title (string, required) - list title
+ top_group (MangaPageGroupDto, required) - manga top page group
+ groups (array[MangaPageGroupDto], required) - manga page groups
+ other_groups (array[MangaPageGroupDto], required) - manga other page groups

## _Result<_Page<SmallAuthorDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<SmallAuthorDto>, required) - response data

## _Page<SmallAuthorDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[SmallAuthorDto], required) - page data

## _Result<_Page<CategoryDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<CategoryDto>, required) - response data

## _Page<CategoryDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[CategoryDto], required) - page data

## _Result<_Page<TinyMangaPageDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<TinyMangaPageDto>, required) - response data

## _Page<TinyMangaPageDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[TinyMangaPageDto], required) - page data

## _Result<MangaPageDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (MangaPageDto, required) - response data

## _Result<MangaChapterDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (MangaChapterDto, required) - response data

## _Result<MangaPageGroupListDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (MangaPageGroupListDto, required) - response data

## _Result<_Page<SmallMangaPageDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<SmallMangaPageDto>, required) - response data

## _Page<SmallMangaPageDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[SmallMangaPageDto], required) - page data
