FORMAT: 1A
HOST: 127.0.0.1:10018/

# manhuagui-api (v1.0.1)

An unofficial backend for manhuagui written in golang/gin.

[Aoi-hosizora - Website](https://github.com/Aoi-hosizora)

[Send email to Aoi-hosizora](mailto:aoihosizora@hotmail.com)

# Group Manga

manga-controller

## Get all mangas [/v1/manga{?page,order,force_refresh}]

> `/v1/manga`

### Get all mangas [GET]

> `GET /v1/manga`

order by popular / new / update

+ Parameters

    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<TinyMangaDto>>)

    + Body

## Get manga [/v1/manga/{mid}{?force_refresh}]

> `/v1/manga/{mid}`

### Get manga [GET]

> `GET /v1/manga/{mid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<MangaDto>)

    + Body

## Get random manga [/v1/manga/random{?force_refresh}]

> `/v1/manga/random`

### Get random manga [GET]

> `GET /v1/manga/random`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<RandomMangaInfoDto>)

    + Body

## Get manga chapter [/v1/manga/{mid}/{cid}{?force_refresh}]

> `/v1/manga/{mid}/{cid}`

### Get manga chapter [GET]

> `GET /v1/manga/{mid}/{cid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)
    + cid (number, required) - manga chapter id
        (format: int64)
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<MangaChapterDto>)

    + Body

# Group MangaList

manga-list-controller

## Get hot serial mangas [/v1/list/serial{?force_refresh}]

> `/v1/list/serial`

### Get hot serial mangas [GET]

> `GET /v1/list/serial`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<MangaGroupListDto>)

    + Body

## Get finished mangas [/v1/list/finish{?force_refresh}]

> `/v1/list/finish`

### Get finished mangas [GET]

> `GET /v1/list/finish`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<MangaGroupListDto>)

    + Body

## Get latest mangas [/v1/list/latest{?force_refresh}]

> `/v1/list/latest`

### Get latest mangas [GET]

> `GET /v1/list/latest`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<MangaGroupListDto>)

    + Body

## Get homepage mangas [/v1/list/homepage{?force_refresh}]

> `/v1/list/homepage`

### Get homepage mangas [GET]

> `GET /v1/list/homepage`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<HomepageMangaGroupListDto>)

    + Body

## Get recent update mangas [/v1/list/updated{?page,limit,force_refresh}]

> `/v1/list/updated`

### Get recent update mangas [GET]

> `GET /v1/list/updated`

+ Parameters

    + page (number, optional) - current page
        (format: int32)
    + limit (number, optional) - page size
        (format: int32)
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<TinyMangaDto>>)

    + Body

# Group Category

category-controller

## Get categories [/v1/category{?force_refresh}]

> `/v1/category`

### Get categories [GET]

> `GET /v1/category`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<CategoryListDto>)

    + Body

## Get genres [/v1/category/genre{?force_refresh}]

> `/v1/category/genre`

### Get genres [GET]

> `GET /v1/category/genre`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<CategoryDto>>)

    + Body

## Get zones [/v1/category/zone{?force_refresh}]

> `/v1/category/zone`

### Get zones [GET]

> `GET /v1/category/zone`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<CategoryDto>>)

    + Body

## Get ages [/v1/category/age{?force_refresh}]

> `/v1/category/age`

### Get ages [GET]

> `GET /v1/category/age`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<CategoryDto>>)

    + Body

## Get genre mangas [/v1/category/genre/{genre}{?zone,age,status,page,order,force_refresh}]

> `/v1/category/genre/{genre}`

### Get genre mangas [GET]

> `GET /v1/category/genre/{genre}`

order by popular / new / update

+ Parameters

    + genre (string, required) - genre name, (all|...)
    + zone (string, optional) - manga zone, (all|japan|hongkong|other|europe|china|korea)
    + age (string, optional) - manga age, (all|shaonv|shaonian|qingnian|ertong|tongyong)
    + status (string, optional) - manga status, (all|lianzai|wanjie)
    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<TinyMangaDto>>)

    + Body

# Group Search

search-controller

## Search mangas [/v1/search{?keyword,page,order,force_refresh}]

> `/v1/search`

### Search mangas [GET]

> `GET /v1/search`

order by popular / new / update

+ Parameters

    + keyword (string, required) - search keyword
    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<SmallMangaDto>>)

    + Body

## Search mangas [/v1/search/{keyword}{?page,order,force_refresh}]

> `/v1/search/{keyword}`

### Search mangas [GET]

> `GET /v1/search/{keyword}`

order by popular / new / update

**Attention: This api is deprecated!**

+ Parameters

    + keyword (string, required) - search keyword
    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<SmallMangaDto>>)

    + Body

# Group Author

author-controller

## Get all authors [/v1/author{?genre,zone,age,page,order,force_refresh}]

> `/v1/author`

### Get all authors [GET]

> `GET /v1/author`

order by popular / comic / update

+ Parameters

    + genre (string, optional) - author genre
    + zone (string, optional) - author zone
    + age (string, optional) - author age range, (shaonv|shaonian|qingnian|ertong|tongyong)
    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<SmallAuthorDto>>)

    + Body

## Get author [/v1/author/{aid}{?force_refresh}]

> `/v1/author/{aid}`

### Get author [GET]

> `GET /v1/author/{aid}`

+ Parameters

    + aid (number, required) - author id
        (format: int64)
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<AuthorDto>)

    + Body

## Get author mangas [/v1/author/{aid}/manga{?page,order,force_refresh}]

> `/v1/author/{aid}/manga`

### Get author mangas [GET]

> `GET /v1/author/{aid}/manga`

order by popular / new / update

+ Parameters

    + aid (number, required) - author id
        (format: int64)
    + page (number, optional) - current page
        (format: int32)
    + order (string, optional) - order string
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<SmallMangaDto>>)

    + Body

# Group Rank

rank-controller

## Get day ranking [/v1/rank/day{?type,force_refresh}]

> `/v1/rank/day`

### Get day ranking [GET]

> `GET /v1/rank/day`

+ Parameters

    + type (string, optional) - manga genre / zone / age, empty or all if all
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<MangaRankDto>>)

    + Body

## Get week ranking [/v1/rank/week{?type,force_refresh}]

> `/v1/rank/week`

### Get week ranking [GET]

> `GET /v1/rank/week`

+ Parameters

    + type (string, optional) - manga genre / zone / age, empty or all if all
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<MangaRankDto>>)

    + Body

## Get month ranking [/v1/rank/month{?type,force_refresh}]

> `/v1/rank/month`

### Get month ranking [GET]

> `GET /v1/rank/month`

+ Parameters

    + type (string, optional) - manga genre / zone / age, empty or all if all
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<MangaRankDto>>)

    + Body

## Get total ranking [/v1/rank/total{?type,force_refresh}]

> `/v1/rank/total`

### Get total ranking [GET]

> `GET /v1/rank/total`

+ Parameters

    + type (string, optional) - manga genre / zone / age, empty or all if all
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<MangaRankDto>>)

    + Body

# Group Comment

comment-controller

## Get manga comments [/v1/comment/manga/{mid}{?page,force_refresh}]

> `/v1/comment/manga/{mid}`

### Get manga comments [GET]

> `GET /v1/comment/manga/{mid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)
    + page (number, optional) - current page
        (format: int32)
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<CommentDto>>)

    + Body

# Group User

user-controller

## Login [/v1/user/login{?username,password}]

> `/v1/user/login`

### Login [POST]

> `POST /v1/user/login`

+ Parameters

    + username (string, required) - login username
    + password (string, required) - login password

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<TokenDto>)

    + Body

## Check login [/v1/user/check_login]

> `/v1/user/check_login`

### Check login [POST]

> `POST /v1/user/check_login`

+ Request (application/json)

    + Headers

            Authorization: (string, required) - access token

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<UsernameDto>)

    + Body

## Get authorized user information [/v1/user/info{?force_refresh}]

> `/v1/user/info`

### Get authorized user information [GET]

> `GET /v1/user/info`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Headers

            Authorization: (string, required) - access token

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<UserDto>)

    + Body

## Record manga for the authorized user [/v1/user/manga/{mid}/{cid}{?force_refresh}]

> `/v1/user/manga/{mid}/{cid}`

### Record manga for the authorized user [GET]

> `GET /v1/user/manga/{mid}/{cid}`

**Attention: This api is deprecated!**

+ Parameters

    + mid (number, required) - manga id
        (format: int64)
    + cid (number, required) - manga chapter id
        (format: int64)
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Headers

            Authorization: (string, required) - access token

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (Result)

    + Body

## Record manga for the authorized user [/v1/user/manga/{mid}/{cid}]

> `/v1/user/manga/{mid}/{cid}`

### Record manga for the authorized user [POST]

> `POST /v1/user/manga/{mid}/{cid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)
    + cid (number, required) - manga chapter id
        (format: int64)

+ Request (application/json)

    + Headers

            Authorization: (string, required) - access token

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (Result)

    + Body

# Group Shelf

shelf-controller

## Get shelf mangas [/v1/shelf{?page,force_refresh}]

> `/v1/shelf`

### Get shelf mangas [GET]

> `GET /v1/shelf`

+ Parameters

    + page (number, optional) - current page
        (format: int32)
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Headers

            Authorization: (string, required) - access token

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<ShelfMangaDto>>)

    + Body

## Check manga in shelf [/v1/shelf/{mid}{?force_refresh}]

> `/v1/shelf/{mid}`

### Check manga in shelf [GET]

> `GET /v1/shelf/{mid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)
    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Headers

            Authorization: (string, required) - access token

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<ShelfStatusDto>)

    + Body

## Save manga to shelf | Remove manga from shelf [/v1/shelf/{mid}]

> `/v1/shelf/{mid}`

### Save manga to shelf [POST]

> `POST /v1/shelf/{mid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)

+ Request (application/json)

    + Headers

            Authorization: (string, required) - access token

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (Result)

    + Body

### Remove manga from shelf [DELETE]

> `DELETE /v1/shelf/{mid}`

+ Parameters

    + mid (number, required) - manga id
        (format: int64)

+ Request (application/json)

    + Headers

            Authorization: (string, required) - access token

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (Result)

    + Body

# Group Message

message-controller

## Get all messages [/v1/message{?force_refresh}]

> `/v1/message`

### Get all messages [GET]

> `GET /v1/message`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<_Page<MessageDto>>)

    + Body

## Get latest message [/v1/message/latest{?force_refresh}]

> `/v1/message/latest`

### Get latest message [GET]

> `GET /v1/message/latest`

+ Parameters

    + force_refresh (boolean, optional) - flag to refresh in force
        + Default: `false`

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    200 OK

    + Attributes (_Result<LatestMessageDto>)

    + Body

# Data Structures

## AuthorDto (object)

+ aid (number, required) - author id
    (format: int64)
+ name (string, required) - author name
+ alias (string, required) - author alias
+ zone (string, required) - author zone
+ cover (string, required) - author cover
+ url (string, required) - author url
+ manga_count (number, required) - author manga count
    (format: int32)
+ newest_manga_id (number, required) - author newest manga id
    (format: int32)
+ newest_manga_title (string, required) - author newest manga title
+ newest_manga_url (string, required) - author newest manga url
+ newest_date (string, required) - author update newest date
+ highest_manga_id (number, required) - author highest manga id
    (format: int32)
+ highest_manga_title (string, required) - author highest manga title
+ highest_manga_url (string, required) - author highest manga url
+ highest_score (number, required) - author highest score
    (format: float)
+ average_score (number, required) - author average score
    (format: float)
+ popularity (number, required) - author popularity
    (format: int32)
+ introduction (string, required) - author introduction
+ related_authors (array[TinyZonedAuthorDto], required) - author related authors

## SmallAuthorDto (object)

+ aid (number, required) - author id
    (format: int64)
+ name (string, required) - author name
+ zone (string, required) - author zone
+ cover (string, required) - author cover
+ url (string, required) - author url
+ manga_count (number, required) - author manga count
    (format: int32)
+ newest_date (string, required) - author update newest date

## TinyAuthorDto (object)

+ aid (number, required) - author id
    (format: int64)
+ name (string, required) - author name
+ url (string, required) - author url

## TinyZonedAuthorDto (object)

+ aid (number, required) - author id
    (format: int64)
+ name (string, required) - author name
+ url (string, required) - author url
+ zone (string, required) - author zone

## CategoryDto (object)

+ name (string, required) - category name
+ title (string, required) - category title
+ url (string, required) - category link
+ cover (string, required) - category cover

## CategoryListDto (object)

+ genres (array[CategoryDto], required) - genre categories
+ zones (array[CategoryDto], required) - zone categories
+ ages (array[CategoryDto], required) - age categories

## CommentDto (object)

+ cid (number, required) - comment id
    (format: int64)
+ uid (number, required) - user id
    (format: int64)
+ username (string, required) - username
+ avatar (string, required) - user avatar
+ gender (number, required) - user gender, 1: Male, 2: Female
    (format: int32)
+ content (string, required) - comment content
+ like_count (number, required) - comment liked count
    (format: int32)
+ reply_count (number, required) - comment reply count
    (format: int32)
+ reply_timeline (array[RepliedCommentDto], required) - comment reply timeline
+ comment_time (string, required) - comment create time

## RepliedCommentDto (object)

+ cid (number, required) - comment id
    (format: int64)
+ uid (number, required) - user id
    (format: int64)
+ username (string, required) - username
+ avatar (string, required) - user avatar
+ gender (number, required) - user gender, 1: Male, 2: Female
    (format: int32)
+ content (string, required) - comment content
+ like_count (number, required) - comment liked count
    (format: int32)
+ reply_count (number, required) - comment reply count
    (format: int32)
+ comment_time (string, required) - comment create time

## MangaDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ title (string, required) - manga name
+ cover (string, required) - manga cover
+ url (string, required) - manga link
+ publish_year (string, required) - manga publish year
+ manga_zone (string, required) - manga zone
+ genres (array[CategoryDto], required) - manga genres
+ authors (array[TinyAuthorDto], required) - manga authors
+ alias (string, required) - manga alias name (deprecated)
+ alias_title (string, required) - manga alias title name (deprecated)
+ aliases (string, required) - manga aliases
+ finished (boolean, required) - manga is finished
+ newest_chapter (string, required) - manga last update chapter
+ newest_date (string, required) - manga last update date
+ brief_introduction (string, required) - manga brief introduction
+ introduction (string, required) - manga introduction
+ manga_rank (string, required) - manga rank
+ score_count (number, required) - manga score count
    (format: int32)
+ average_score (number, required) - manga average score
    (format: float)
+ per_scores (array[string], required) - manga per scores, skip 0, from 1 to 5
+ banned (boolean, required) - manga is banned
+ copyright (boolean, required) - has copyright
+ chapter_groups (array[MangaChapterGroupDto], required) - manga chapter groups

## MangaChapterDto (object)

+ cid (number, required) - chapter id
    (format: int64)
+ title (string, required) - chapter name
+ mid (number, required) - manga id
    (format: int64)
+ manga_title (string, required) - manga name
+ manga_cover (string, required) - manga cover
+ manga_url (string, required) - manga link
+ url (string, required) - chapter link
+ pages (array[string], required) - chapter pages
+ page_count (number, required) - chapter pages count
    (format: int32)
+ next_cid (number, required) - next chapter id
    (format: int64)
+ prev_cid (number, required) - prev chapter id
    (format: int64)
+ copyright (boolean, required) - has copyright

## SmallMangaDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ title (string, required) - manga name
+ cover (string, required) - manga cover
+ url (string, required) - manga link
+ publish_year (string, required) - manga publish year
+ manga_zone (string, required) - manga zone
+ genres (array[CategoryDto], required) - manga genres
+ authors (array[TinyAuthorDto], required) - manga authors
+ finished (boolean, required) - manga is finished
+ newest_chapter (string, required) - manga last update chapter
+ newest_date (string, required) - manga last update date
+ brief_introduction (string, required) - manga brief introduction

## TinyMangaDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ title (string, required) - manga name
+ cover (string, required) - manga cover
+ url (string, required) - manga link
+ finished (boolean, required) - manga is finished
+ newest_chapter (string, required) - manga last update chapter
+ newest_date (string, required) - manga last update date

## TinyMangaChapterDto (object)

+ cid (number, required) - chapter id
    (format: int64)
+ title (string, required) - chapter name
+ mid (number, required) - manga id
    (format: int64)
+ url (string, required) - chapter link
+ page_count (number, required) - chapter pages count
    (format: int32)
+ is_new (boolean, required) - chapter is uploaded newly
+ group (string, required) - chapter group
+ number (boolean, required) - chapter number

## TinyBlockMangaDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ title (string, required) - manga name
+ cover (string, required) - manga cover
+ url (string, required) - manga link
+ finished (boolean, required) - manga is finished
+ newest_chapter (string, required) - manga last update chapter

## RandomMangaInfoDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ url (number, required) - manga link
    (format: int64)

## MangaGroupDto (object)

+ title (string, required) - group title
+ mangas (array[TinyBlockMangaDto], required) - group mangas

## MangaChapterGroupDto (object)

+ title (string, required) - group title
+ chapters (array[TinyMangaChapterDto], required) - group chapters

## MangaGroupListDto (object)

+ title (string, required) - list title
+ top_group (MangaGroupDto, required) - manga top page group
+ groups (array[MangaGroupDto], required) - manga groups
+ other_groups (array[MangaGroupDto], required) - manga other page groups

## HomepageMangaGroupListDto (object)

+ serial (MangaGroupListDto, required) - homepage serial manga group list
+ finish (MangaGroupListDto, required) - homepage finish group list
+ latest (MangaGroupListDto, required) - homepage latest manga group list
+ daily (array[MangaRankDto], required) - manga daily ranking for homepage
+ genres (array[CategoryDto], required) - manga all genres for homepage
+ zones (array[CategoryDto], required) - manga all zones for homepage
+ ages (array[CategoryDto], required) - manga all ages for homepage

## MangaRankDto (object)

+ mid (number, required) - rank manga id
    (format: int64)
+ title (string, required) - rank manga title
+ url (string, required) - rank manga url
+ finished (boolean, required) - rank manga is finished
+ authors (string, required) - rank manga authors
+ newest_chapter (string, required) - rank manga newest chapter
+ newest_date (string, required) - rank manga newest date
+ order (number, required) - rank order
    (format: int32)
+ score (number, required) - rank manga score
    (format: float)
+ trend (number, required) - rank trend, 0: None, 1: Up, 2: Down
    (format: int32)

## ShelfMangaDto (object)

+ mid (number, required) - manga id
    (format: int64)
+ title (string, required) - manga name
+ cover (string, required) - manga cover
+ url (string, required) - manga link
+ newest_chapter (string, required) - manga last update chapter
+ newest_duration (string, required) - manga last update duration
+ last_chapter (string, required) - manga last read chapter
+ last_duration (string, required) - manga last read duration

## MessageDto (object)

+ mid (number, required) - message id
    (format: int64)
+ title (string, required) - message title
+ notification (NotificationContentDto, required) - notification content
    (allow empty value)
+ new_version (NewVersionContentDto, required) - new version content
    (allow empty value)
+ created_at (string, required) - created time
    (format: date-time)
+ updated_at (string, required) - updated time
    (format: date-time)

## NotificationContentDto (object)

+ content (string, required) - notification content
+ dismissible (boolean, required) - flag if the message is dismissible
+ link (boolean, required) - link associated to the message

## NewVersionContentDto (object)

+ version (string, required) - version string
+ must_upgrade (boolean, required) - flag if must be upgrade
+ change_logs (string, required) - version change logs
+ release_page (string, required) - version release page

## LatestMessageDto (object)

+ notification (MessageDto, required) - latest notification message
+ new_version (MessageDto, required) - latest new version message
+ not_dismissible_notification (MessageDto, required) - latest notification message (not dismissible)
+ must_upgrade_new_version (MessageDto, required) - latest new version message (must upgrade)

## TokenDto (object)

+ token (string, required) - access token

## UserDto (object)

+ username (string, required) - user name
+ avatar (string, required) - user avatar
+ class (string, required) - user class (会员等级)
+ score (number, required) - user score (个人成长值)
    (format: int32)
+ account_point (number, required) - user account point (账户积分)
    (format: int32)
+ unread_message_count (number, required) - unread message count)
    (format: int32)
+ login_ip (string, required) - user current login ip
+ last_login_ip (string, required) - user last login ip
+ register_time (string, required) - user register time
+ last_login_time (string, required) - user last login time
+ cumulative_day_count (string, required) - user cumulative logined day count
+ total_comment_count (string, required) - user total comment count

## UsernameDto (object)

+ username (string, required) - username

## ShelfStatusDto (object)

+ in (boolean, required) - manga is in the shelf
+ count (number, required) - manga starred count
    (format: int32)

## Result (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message

## _Page<SmallAuthorDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[SmallAuthorDto], required) - page data

## _Result<_Page<SmallAuthorDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<SmallAuthorDto>, required) - response data

## _Result<AuthorDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (AuthorDto, required) - response data

## _Page<SmallMangaDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[SmallMangaDto], required) - page data

## _Result<_Page<SmallMangaDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<SmallMangaDto>, required) - response data

## _Result<CategoryListDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (CategoryListDto, required) - response data

## _Page<CategoryDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[CategoryDto], required) - page data

## _Result<_Page<CategoryDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<CategoryDto>, required) - response data

## _Page<TinyMangaDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[TinyMangaDto], required) - page data

## _Result<_Page<TinyMangaDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<TinyMangaDto>, required) - response data

## _Page<CommentDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[CommentDto], required) - page data

## _Result<_Page<CommentDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<CommentDto>, required) - response data

## _Result<MangaDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (MangaDto, required) - response data

## _Result<RandomMangaInfoDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (RandomMangaInfoDto, required) - response data

## _Result<MangaChapterDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (MangaChapterDto, required) - response data

## _Result<MangaGroupListDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (MangaGroupListDto, required) - response data

## _Result<HomepageMangaGroupListDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (HomepageMangaGroupListDto, required) - response data

## _Page<MessageDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[MessageDto], required) - page data

## _Result<_Page<MessageDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<MessageDto>, required) - response data

## _Result<LatestMessageDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (LatestMessageDto, required) - response data

## _Page<MangaRankDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[MangaRankDto], required) - page data

## _Result<_Page<MangaRankDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<MangaRankDto>, required) - response data

## _Page<ShelfMangaDto> (object)

+ page (number, required) - current page
    (format: int32)
+ limit (number, required) - page size
    (format: int32)
+ total (number, required) - data count
    (format: int32)
+ data (array[ShelfMangaDto], required) - page data

## _Result<_Page<ShelfMangaDto>> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (_Page<ShelfMangaDto>, required) - response data

## _Result<ShelfStatusDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (ShelfStatusDto, required) - response data

## _Result<TokenDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (TokenDto, required) - response data

## _Result<UsernameDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (UsernameDto, required) - response data

## _Result<UserDto> (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
+ data (UserDto, required) - response data
